### ISSUE TITLE
NSBCA generated by Creative Studio doesn't seem to work for the starter selection scene.

### ISSUE THREAD

**Issue by BromBromBromley** [kingdom-of-ds-hacking/CTRMapV#5] opened 2023-10-16 01:35 UTC
This is an extension of the issue I put in the CTRMapV repo, but while the NSBCA now does correctly display within the editor, it seems that they don't necessarily work correctly for the starter selection scene. In order to make sure it wasn't an issue of my own model, I tested with re-exporting the NSBCA of Bianca's animation with Creative Studio and replacing the original file, file 35 in a202, with it. Upon doing this, when loading the starter selection scene, it crashes. Here is the original NSBCA and the generated NSBCA by comparison in the zip file. I have included the original NSBMD of Bianca as well for reference.

[nsbca_files.zip](https://github.com/kingdom-of-ds-hacking/CTRMap-CE/files/12911277/nsbca_files.zip)

**Comment by HelloOO7** [comment] 2023-10-16 08:26
Transferred this to CTRMapV since the NSBCA exporter is part of that repo.

Can you provide a CPU register + memory dump at the time of the crash?

**Comment by BromBromBromley** [comment] 2023-10-16 23:41
Ah, apologies for the wrong repo.

Here's the CPU register dump from the NitroKernel DLL:
```
CPSR: 0x4000003F
R0:   0x00007FF7
R1:   0x00000000
R2:   0x022A7FAC
R3:   0x022A7F98
R4:   0x03068044
R5:   0x02FE33E0
R6:   0x00000000
R7:   0x022A7F98
R8:   0x0000000B
R9:   0x022BB0AC
R10:  0x02FE365C
R11:  0x00000000
R12:  0x02FE34F0
SP:   0x02FE33B0
LR:   0x02068C2D
PC:   0x02058F92
```

Here's the RAM dump from Desmume (MelonDS doesn't have this feature from what I can tell)
[ram_dump.zip](https://github.com/kingdom-of-ds-hacking/CTRMapV/files/12922807/ram_dump.zip)

**Comment by HelloOO7** [comment] 2023-10-17 17:01
I think you might've accidentally uploaded the wrong NSBCA; the "generated.nsbca" file contains an animation called gym_rep (Bianca should be psel_s02) and does not fit on any Bianca skeleton I could find.

However, I did make some changes to the exporter based on differences I could notice in the files and the register dump - it seems like the second (historically unknown) value on the scale track is an inverse scale. When I loaded the original NSBCA you sent, exported it as DAE, imported it back and then re-rexported into the game with the values properly calculated, everything seems to have worked fine.

Here's the build I used: https://drive.google.com/file/d/1RAjgL3PufJDnzEJJaK2EIQHYsZYY3nl0/view?usp=drive_link

**Comment by BromBromBromley** [comment] 2023-10-17 21:34
Oops, my apologies for sending the wrong NSBCA!

This build seems to work for me now at least with the original psel_s02 with Bianca. The animation that I imported from my own model, though, still seems to crash on MelonDS with slightly different results with the contents of R2, R3, R4, R7, and R9.

```
CPSR: 0x4000003F
R0:   0x00007FF7
R1:   0x00000000
R2:   0x022A8030
R3:   0x022A801C
R4:   0x030280C4
R5:   0x02FE33E0
R6:   0x00000000
R7:   0x022A801C
R8:   0x0000000B
R9:   0x022C1470
R10:  0x02FE365C
R11:  0x00000000
R12:  0x02FE34F0
SP:   0x02FE33B0
LR:   0x02068C2D
PC:   0x02058F92
```

On Desmume, while it does go into the starter scene, it seems to display improperly.
![desmume_2023-10-17_17-27-31](https://github.com/kingdom-of-ds-hacking/CTRMapV/assets/20919448/49834310-75dc-48ff-865a-b89f4a4e2b77)

Here is a RAM dump for the part where it says "What Pokémon will you choose?" since it doesn't crash on Desmume.
[ram_dump.zip](https://github.com/kingdom-of-ds-hacking/CTRMapV/files/12961979/ram_dump.zip)

Here's the CMIF for the model.
[yowch.zip](https://github.com/kingdom-of-ds-hacking/CTRMapV/files/12964143/yowch.zip)

A friend who had similar issues with a model (granted on the 3DS) said it may have been an issue with the vertex groups as a potential point of reference.

**Comment by HelloOO7** [comment] 2023-10-18 22:12
Unfortunately, I can not debug this further if the issue only appears on MelonDS, as the CPU state is not enough to describe the problem accurately and I'm not willing to subject myself to the modern day waterboarding that is building the MelonDS GDB stub on Windows.

However this does seem like it may be undefined behavior caused externally (perhaps by the model data), as the animation seems to work okay if certain data is hand-edited to target different bones.

I will keep this open but don't expect much.

**Comment by BromBromBromley** [comment] 2023-10-20 04:29
Luckily, Plat went through the modern day waterboarding a few months ago with the [MelonDS GDB stub for windows](https://cdn.discordapp.com/attachments/446865033310240769/1141226927869394944/melonDS-GDB.zip). I think it likely is an issue with the model data, though. With vertex groups for bones, is there an issue if there are vertex groups and bones with no assigned vertices?

Also what target bones did you change for the animation? I'd like to know for the sake of having a clearer basis of what might be incorrect with the initial model data.

**Comment by HelloOO7** [comment] 2023-10-20 06:58
I appreciate the favour, however, the GDB stub build you sent seems to have been built from an older checkout of the branch, so it does not support single-stepping and is not of much use to me. Not to mention that it appears that some fixes have to be done to make that work with IDA.

There isn't such a thing as vertex groups on the DS, that's just a Blender-specific concept. If there are bones with no vertices assigned, no render commands are emitted for them, so it's as if they did not exist to the renderer.

I swapped the animations of bones 0xD and 0x11, but I did it as a test through a hex editor, so I do not think it is a higher-level related issue.

**Comment by BromBromBromley** [comment] 2023-10-21 18:51
I figured out the issue! It seemed the issue came from not every bone having a target in the animation. Once I gave a target to everything, it now works correctly, even on MelonDS. Thanks again for your help, Hello!

**Comment by HelloOO7** [comment] 2023-10-21 19:24
It is really odd that an animation only works if it targets all bones. I'm reopening this inasmuch as it isn't expected behavior. We'll see about it when the GDB stub on MelonDS matures.

**Comment by HelloOO7** [comment] 2023-10-22 13:44
Upon further inspection, this seems to be a bug in Nintendo's graphics resource library. All run-time animation structures use the `TargetInfo` array to match model element indices with animation transforms. This works correctly on material animations (0x2069C90), where the animation loader properly populates the array so that `arr[matIndex]` points to the correct transform for the material. However, on skeletal animations (0x2068790), the loading code instead of storing `TargetInfo[anm->Transforms[i]->TargetJoint] = i` writes `TargetInfo[i] = anm->Transforms[i]->TargetJoint` and only ever uses that to notify the model that a joint is animated (not for actually matching the transforms). Thus, all animation code works as intended only if the number and order of transforms on the animation matches the model.

It would be best to fix this using code injection as it would allow to save a considerable amount of space on animations through means that the format already supports (but can't properly use because of the bug), but for now I'll add an option to turn these optimizations off so that the generated animations retain compatibility with retail code.

**Comment by HelloOO7** [comment] 2023-10-22 14:31
Can you verify if using the "Target all bones" option in the export settings in [this build](https://drive.google.com/file/d/14vRALisyHsu6RXh0J0msXPIMX9mKmUMC/view?usp=share_link) now fixes the issue regardless of whether the animation contained a transform for every bone?

**Comment by BromBromBromley** [comment] 2023-10-22 19:53
OK, with that build, it seems to fix the issue even if a transform wasn't given to a bone that I removed.

**Comment by HelloOO7** [comment] 2023-10-22 20:15
Great! Release 1.1.4 should have this fix included.

**Closed as completed by HelloOO7** 2023-10-22 20:15 UTC
