### ISSUE TITLE
BW PokéScript commands are out of date

### ISSUE THREAD

**Issue by BromBromBromley** [kingdom-of-ds-hacking/CTRMapV#7] opened 2024-12-11 18:58 UTC
When I was helping someone today with scripting on BW, I noticed that some of the script commands are out of date such as Message.Actor() still being Message.NPCMsg() or Input.LastKeyWait() being Interact.LastKeyWait(). These function properly when the name is changed, however, but I think it could cause some confusion.

**Comment by HelloOO7** [comment] 2024-12-13 16:35
Thank you for the notice. Does this also apply to BW2 in some part, or is it just BW?

**Comment by BromBromBromley** [comment] 2024-12-13 16:36
I believe just BW right now.

**Comment by HelloOO7** [comment] 2024-12-13 17:27
Should be fixed in release 1.3.0.

**Comment by BromBromBromley** [comment] 2024-12-13 18:15
It seems a majority of the commands have been corrected, thanks! It seems that EventWorks.Get() and EventWorks.Set() are still EventWorks.WorkGet() and EventWorks.WorkSet(), though.

**Comment by HelloOO7** [comment] 2024-12-13 18:23
That is how they are defined in the Google Sheet that the header files are generated from.

**Comment by BromBromBromley** [comment] 2024-12-13 18:38
At least on the B2W2 one, it seems that matches the BeaterScript/SAK name, but the PokéScript name shows as Get() and Set() respectively. I haven't seen the BW version of the script command sheet, though, my apologies.
![image](https://github.com/user-attachments/assets/f7f3448d-91b3-4f5a-8bd8-e4cec3ec633b)
Additionally, when CTRMap decompiles a script, it also decompiles them as Get() and Set() but then complains because they are not WorkGet() and WorkSet().

**Comment by HelloOO7** [comment] 2024-12-13 18:47
You are correct, the B2W2 table has the names set correctly. On BW, they are wrong for some reason. I have not been following either sheet for the past 2 years though. The behavior you are reporting is expected, the problem is in the data in the google sheet.

**Comment by BromBromBromley** [comment] 2024-12-15 08:25
I see. Will those be updated to match?
Also, it seems that after the update, commands from the Base package no longer appear to get resolved correctly even though the autocompletion works correctly.

**Comment by HelloOO7** [comment] 2024-12-15 08:54
> Will those be updated to match?

That's not strictly up for me to decide, but if it's just about changing workset/get, I can probably push that into the google sheets myself.

> commands from the Base package no longer appear to get resolved correctly

On BW or BW2 as well?

**Comment by BromBromBromley** [comment] 2024-12-15 09:06
1. I see. It is primarily just about that given that it decompiles to just
Get() and Set() then immediately complains about not being able to resolve
it which is the main reason that I think the change would be good.
2. I know for certain this applies to B2W2, but I forget for BW, my
apologies.

**Comment by HelloOO7** [comment] 2024-12-16 16:32
I have changed WorkSet and WorkGet in the google sheet as requested and updated the libraries accordingly.

As for the issue with the Base package, the reason why it comes up is because it seems that someone very uncautious renamed certain parameters in the Google sheet to "parameter (?)", with a question mark character as part of the parameter name. That makes the Base.pks file not compile, and it is why you are seeing the "Unresolved import" error, because the file you are importing is not recognized as valid PokéScript source code.

I edited the BW2 sheet to remove the invalid characters and added a note to the header that names must be C-style identifiers (otherwise PokéScript will throw a syntax error).

Both should be fixed in the release under the same tag.

**Comment by BromBromBromley** [comment] 2024-12-16 18:13
I see, thank you.

Given that syncing commands directly uses the data on the spreadsheet, are
there any other things to keep in mind when modifying it?

I will say, I don't think it's the most fair saying someone is uncautious
if prior to now there was little in terms of communicating certain
considerations one should keep in mind in terms of modifying the sheet.

If I was the one who accidentally added "(?)," my apologies for the
trouble, at least.

**Comment by HelloOO7** [comment] 2024-12-16 18:22
Yeah, I'd guess that if someone added "\*/" into the function brief, it would also break the syntax in unwieldy ways, because that is the C comment terminator. Same would happen with "/\*" or gaps in the function name, etc.; more could be deduced similarly. Generally, keep in mind that everything eventually gets generated into source code with no sanitization in place, as it is kind of taken for granted that there will not (hopefully lol) be any malicious actors pushing rootkits into the google sheets.

**Comment by BromBromBromley** [comment] 2024-12-16 18:41
I see, thanks for the clarification!

**Closed as completed** 2024-12-16 23:00 UTC
